package net.greenjab.nekomasfixed.util;

import net.greenjab.nekomasfixed.registry.registries.BlockRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;

import java.util.EnumMap;

public class BlockDyeMap {
    public static final EnumMap<AllDyes, Block> BRICKS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_SLAB = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_STAIRS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BRICK_WALL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> TERRACOTTA = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> STAINED_GLASS = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> STAINED_GLASS_PANE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> WOOL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SPOTTED_WOOL = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CARPET = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SPOTTED_CARPET = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> GLAZED_TERRACOTTA = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CANDLE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CONCRETE = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> CONCRETE_POWDER = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> FROGLIGHT = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> SHULKER_BOX = new EnumMap<>(AllDyes.class);
    public static final EnumMap<AllDyes, Block> BED = new EnumMap<>(AllDyes.class);

    //this class provides all the mappings for both datagen and server side logic... its used by tagProvider and DyedBRushItem

    static {
        WOOL.put(AllDyes.WHITE, Blocks.WHITE_WOOL);
        WOOL.put(AllDyes.ORANGE, Blocks.ORANGE_WOOL);
        WOOL.put(AllDyes.MAGENTA, Blocks.MAGENTA_WOOL);
        WOOL.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_WOOL);
        WOOL.put(AllDyes.YELLOW, Blocks.YELLOW_WOOL);
        WOOL.put(AllDyes.LIME, Blocks.LIME_WOOL);
        WOOL.put(AllDyes.PINK, Blocks.PINK_WOOL);
        WOOL.put(AllDyes.GRAY, Blocks.GRAY_WOOL);
        WOOL.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_WOOL);
        WOOL.put(AllDyes.CYAN, Blocks.CYAN_WOOL);
        WOOL.put(AllDyes.PURPLE, Blocks.PURPLE_WOOL);
        WOOL.put(AllDyes.BLUE, Blocks.BLUE_WOOL);
        WOOL.put(AllDyes.BROWN, Blocks.BROWN_WOOL);
        WOOL.put(AllDyes.GREEN, Blocks.GREEN_WOOL);
        WOOL.put(AllDyes.RED, Blocks.RED_WOOL);
        WOOL.put(AllDyes.BLACK, Blocks.BLACK_WOOL);
        WOOL.put(AllDyes.AMBER, BlockRegistry.AMBER_WOOL);
        WOOL.put(AllDyes.AQUA, BlockRegistry.AQUA_WOOL);
        WOOL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_WOOL);
        WOOL.put(AllDyes.MAROON, BlockRegistry.MAROON_WOOL);

        SPOTTED_WOOL.put(AllDyes.WHITE, BlockRegistry.WHITE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.ORANGE, BlockRegistry.ORANGE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.YELLOW, BlockRegistry.YELLOW_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIME, BlockRegistry.LIME_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.PINK, BlockRegistry.PINK_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.GRAY, BlockRegistry.GRAY_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.CYAN, BlockRegistry.CYAN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.PURPLE, BlockRegistry.PURPLE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BLUE, BlockRegistry.BLUE_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BROWN, BlockRegistry.BROWN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.GREEN, BlockRegistry.GREEN_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.RED, BlockRegistry.RED_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.BLACK, BlockRegistry.BLACK_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.AMBER, BlockRegistry.AMBER_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.AQUA, BlockRegistry.AQUA_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SPOTTED_WOOL);
        SPOTTED_WOOL.put(AllDyes.MAROON, BlockRegistry.MAROON_SPOTTED_WOOL);

        CONCRETE.put(AllDyes.WHITE, Blocks.WHITE_CONCRETE);
        CONCRETE.put(AllDyes.ORANGE, Blocks.ORANGE_CONCRETE);
        CONCRETE.put(AllDyes.MAGENTA, Blocks.MAGENTA_CONCRETE);
        CONCRETE.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE);
        CONCRETE.put(AllDyes.YELLOW, Blocks.YELLOW_CONCRETE);
        CONCRETE.put(AllDyes.LIME, Blocks.LIME_CONCRETE);
        CONCRETE.put(AllDyes.PINK, Blocks.PINK_CONCRETE);
        CONCRETE.put(AllDyes.GRAY, Blocks.GRAY_CONCRETE);
        CONCRETE.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE);
        CONCRETE.put(AllDyes.CYAN, Blocks.CYAN_CONCRETE);
        CONCRETE.put(AllDyes.PURPLE, Blocks.PURPLE_CONCRETE);
        CONCRETE.put(AllDyes.BLUE, Blocks.BLUE_CONCRETE);
        CONCRETE.put(AllDyes.BROWN, Blocks.BROWN_CONCRETE);
        CONCRETE.put(AllDyes.GREEN, Blocks.GREEN_CONCRETE);
        CONCRETE.put(AllDyes.RED, Blocks.RED_CONCRETE);
        CONCRETE.put(AllDyes.BLACK, Blocks.BLACK_CONCRETE);
        CONCRETE.put(AllDyes.AMBER, BlockRegistry.AMBER_CONCRETE);
        CONCRETE.put(AllDyes.AQUA, BlockRegistry.AQUA_CONCRETE);
        CONCRETE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CONCRETE);
        CONCRETE.put(AllDyes.MAROON, BlockRegistry.MAROON_CONCRETE);

        CONCRETE_POWDER.put(AllDyes.WHITE, Blocks.WHITE_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.ORANGE, Blocks.ORANGE_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.MAGENTA, Blocks.MAGENTA_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.YELLOW, Blocks.YELLOW_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.LIME, Blocks.LIME_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.PINK, Blocks.PINK_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.GRAY, Blocks.GRAY_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.CYAN, Blocks.CYAN_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.PURPLE, Blocks.PURPLE_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.BLUE, Blocks.BLUE_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.BROWN, Blocks.BROWN_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.GREEN, Blocks.GREEN_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.RED, Blocks.RED_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.BLACK, Blocks.BLACK_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.AMBER, BlockRegistry.AMBER_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.AQUA, BlockRegistry.AQUA_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CONCRETE_POWDER);
        CONCRETE_POWDER.put(AllDyes.MAROON, BlockRegistry.MAROON_CONCRETE_POWDER);

        CARPET.put(AllDyes.WHITE, Blocks.WHITE_CARPET);
        CARPET.put(AllDyes.ORANGE, Blocks.ORANGE_CARPET);
        CARPET.put(AllDyes.MAGENTA, Blocks.MAGENTA_CARPET);
        CARPET.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_CARPET);
        CARPET.put(AllDyes.YELLOW, Blocks.YELLOW_CARPET);
        CARPET.put(AllDyes.LIME, Blocks.LIME_CARPET);
        CARPET.put(AllDyes.PINK, Blocks.PINK_CARPET);
        CARPET.put(AllDyes.GRAY, Blocks.GRAY_CARPET);
        CARPET.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_CARPET);
        CARPET.put(AllDyes.CYAN, Blocks.CYAN_CARPET);
        CARPET.put(AllDyes.PURPLE, Blocks.PURPLE_CARPET);
        CARPET.put(AllDyes.BLUE, Blocks.BLUE_CARPET);
        CARPET.put(AllDyes.BROWN, Blocks.BROWN_CARPET);
        CARPET.put(AllDyes.GREEN, Blocks.GREEN_CARPET);
        CARPET.put(AllDyes.RED, Blocks.RED_CARPET);
        CARPET.put(AllDyes.BLACK, Blocks.BLACK_CARPET);
        CARPET.put(AllDyes.AMBER, BlockRegistry.AMBER_CARPET);
        CARPET.put(AllDyes.AQUA, BlockRegistry.AQUA_CARPET);
        CARPET.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CARPET);
        CARPET.put(AllDyes.MAROON, BlockRegistry.MAROON_CARPET);

        SPOTTED_CARPET.put(AllDyes.WHITE, BlockRegistry.WHITE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.ORANGE, BlockRegistry.ORANGE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.YELLOW, BlockRegistry.YELLOW_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIME, BlockRegistry.LIME_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.PINK, BlockRegistry.PINK_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.GRAY, BlockRegistry.GRAY_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.CYAN, BlockRegistry.CYAN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.PURPLE, BlockRegistry.PURPLE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BLUE, BlockRegistry.BLUE_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BROWN, BlockRegistry.BROWN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.GREEN, BlockRegistry.GREEN_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.RED, BlockRegistry.RED_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.BLACK, BlockRegistry.BLACK_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.AMBER, BlockRegistry.AMBER_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.AQUA, BlockRegistry.AQUA_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SPOTTED_CARPET);
        SPOTTED_CARPET.put(AllDyes.MAROON, BlockRegistry.MAROON_SPOTTED_CARPET);

        CANDLE.put(AllDyes.WHITE, Blocks.WHITE_CANDLE);
        CANDLE.put(AllDyes.ORANGE, Blocks.ORANGE_CANDLE);
        CANDLE.put(AllDyes.MAGENTA, Blocks.MAGENTA_CANDLE);
        CANDLE.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_CANDLE);
        CANDLE.put(AllDyes.YELLOW, Blocks.YELLOW_CANDLE);
        CANDLE.put(AllDyes.LIME, Blocks.LIME_CANDLE);
        CANDLE.put(AllDyes.PINK, Blocks.PINK_CANDLE);
        CANDLE.put(AllDyes.GRAY, Blocks.GRAY_CANDLE);
        CANDLE.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_CANDLE);
        CANDLE.put(AllDyes.CYAN, Blocks.CYAN_CANDLE);
        CANDLE.put(AllDyes.PURPLE, Blocks.PURPLE_CANDLE);
        CANDLE.put(AllDyes.BLUE, Blocks.BLUE_CANDLE);
        CANDLE.put(AllDyes.BROWN, Blocks.BROWN_CANDLE);
        CANDLE.put(AllDyes.GREEN, Blocks.GREEN_CANDLE);
        CANDLE.put(AllDyes.RED, Blocks.RED_CANDLE);
        CANDLE.put(AllDyes.BLACK, Blocks.BLACK_CANDLE);
        CANDLE.put(AllDyes.AMBER, BlockRegistry.AMBER_CANDLE);
        CANDLE.put(AllDyes.AQUA, BlockRegistry.AQUA_CANDLE);
        CANDLE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_CANDLE);
        CANDLE.put(AllDyes.MAROON, BlockRegistry.MAROON_CANDLE);

        GLAZED_TERRACOTTA.put(AllDyes.WHITE, Blocks.WHITE_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.ORANGE, Blocks.ORANGE_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.MAGENTA, Blocks.MAGENTA_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.YELLOW, Blocks.YELLOW_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.LIME, Blocks.LIME_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.PINK, Blocks.PINK_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.GRAY, Blocks.GRAY_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.CYAN, Blocks.CYAN_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.PURPLE, Blocks.PURPLE_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.BLUE, Blocks.BLUE_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.BROWN, Blocks.BROWN_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.GREEN, Blocks.GREEN_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.RED, Blocks.RED_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.BLACK, Blocks.BLACK_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.AMBER, BlockRegistry.AMBER_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.AQUA, BlockRegistry.AQUA_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.INDIGO, BlockRegistry.INDIGO_GLAZED_TERRACOTTA);
        GLAZED_TERRACOTTA.put(AllDyes.MAROON, BlockRegistry.MAROON_GLAZED_TERRACOTTA);

        BRICKS.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICKS);
        BRICKS.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICKS);
        BRICKS.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICKS);
        BRICKS.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICKS);
        BRICKS.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICKS);
        BRICKS.put(AllDyes.LIME, BlockRegistry.LIME_BRICKS);
        BRICKS.put(AllDyes.PINK, BlockRegistry.PINK_BRICKS);
        BRICKS.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICKS);
        BRICKS.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICKS);
        BRICKS.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICKS);
        BRICKS.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICKS);
        BRICKS.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICKS);
        BRICKS.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICKS);
        BRICKS.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICKS);
        BRICKS.put(AllDyes.RED, BlockRegistry.RED_BRICKS);
        BRICKS.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICKS);
        BRICKS.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICKS);
        BRICKS.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICKS);
        BRICKS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICKS);
        BRICKS.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICKS);

        BRICK_SLAB.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.RED, BlockRegistry.RED_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_SLAB);
        BRICK_SLAB.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_SLAB);

        BRICK_STAIRS.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.RED, BlockRegistry.RED_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_STAIRS);
        BRICK_STAIRS.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_STAIRS);

        BRICK_WALL.put(AllDyes.WHITE, BlockRegistry.WHITE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.ORANGE, BlockRegistry.ORANGE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.MAGENTA, BlockRegistry.MAGENTA_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIGHT_BLUE, BlockRegistry.LIGHT_BLUE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.YELLOW, BlockRegistry.YELLOW_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIME, BlockRegistry.LIME_BRICK_WALL);
        BRICK_WALL.put(AllDyes.PINK, BlockRegistry.PINK_BRICK_WALL);
        BRICK_WALL.put(AllDyes.GRAY, BlockRegistry.GRAY_BRICK_WALL);
        BRICK_WALL.put(AllDyes.LIGHT_GRAY, BlockRegistry.LIGHT_GRAY_BRICK_WALL);
        BRICK_WALL.put(AllDyes.CYAN, BlockRegistry.CYAN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.PURPLE, BlockRegistry.PURPLE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BLUE, BlockRegistry.BLUE_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BROWN, BlockRegistry.BROWN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.GREEN, BlockRegistry.GREEN_BRICK_WALL);
        BRICK_WALL.put(AllDyes.RED, BlockRegistry.RED_BRICK_WALL);
        BRICK_WALL.put(AllDyes.BLACK, BlockRegistry.BLACK_BRICK_WALL);
        BRICK_WALL.put(AllDyes.AMBER, BlockRegistry.AMBER_BRICK_WALL);
        BRICK_WALL.put(AllDyes.AQUA, BlockRegistry.AQUA_BRICK_WALL);
        BRICK_WALL.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BRICK_WALL);
        BRICK_WALL.put(AllDyes.MAROON, BlockRegistry.MAROON_BRICK_WALL);

        TERRACOTTA.put(AllDyes.WHITE, Blocks.WHITE_TERRACOTTA);
        TERRACOTTA.put(AllDyes.ORANGE, Blocks.ORANGE_TERRACOTTA);
        TERRACOTTA.put(AllDyes.MAGENTA, Blocks.MAGENTA_TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_TERRACOTTA);
        TERRACOTTA.put(AllDyes.YELLOW, Blocks.YELLOW_TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIME, Blocks.LIME_TERRACOTTA);
        TERRACOTTA.put(AllDyes.PINK, Blocks.PINK_TERRACOTTA);
        TERRACOTTA.put(AllDyes.GRAY, Blocks.GRAY_TERRACOTTA);
        TERRACOTTA.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_TERRACOTTA);
        TERRACOTTA.put(AllDyes.CYAN, Blocks.CYAN_TERRACOTTA);
        TERRACOTTA.put(AllDyes.PURPLE, Blocks.PURPLE_TERRACOTTA);
        TERRACOTTA.put(AllDyes.BLUE, Blocks.BLUE_TERRACOTTA);
        TERRACOTTA.put(AllDyes.BROWN, Blocks.BROWN_TERRACOTTA);
        TERRACOTTA.put(AllDyes.GREEN, Blocks.GREEN_TERRACOTTA);
        TERRACOTTA.put(AllDyes.RED, Blocks.RED_TERRACOTTA);
        TERRACOTTA.put(AllDyes.BLACK, Blocks.BLACK_TERRACOTTA);
        TERRACOTTA.put(AllDyes.AMBER, BlockRegistry.AMBER_TERRACOTTA);
        TERRACOTTA.put(AllDyes.AQUA, BlockRegistry.AQUA_TERRACOTTA);
        TERRACOTTA.put(AllDyes.INDIGO, BlockRegistry.INDIGO_TERRACOTTA);
        TERRACOTTA.put(AllDyes.MAROON, BlockRegistry.MAROON_TERRACOTTA);

        STAINED_GLASS.put(AllDyes.WHITE, Blocks.WHITE_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.ORANGE, Blocks.ORANGE_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.MAGENTA, Blocks.MAGENTA_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.YELLOW, Blocks.YELLOW_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.LIME, Blocks.LIME_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.PINK, Blocks.PINK_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.GRAY, Blocks.GRAY_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.CYAN, Blocks.CYAN_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.PURPLE, Blocks.PURPLE_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.BLUE, Blocks.BLUE_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.BROWN, Blocks.BROWN_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.GREEN, Blocks.GREEN_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.RED, Blocks.RED_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.BLACK, Blocks.BLACK_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.AMBER, BlockRegistry.AMBER_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.AQUA, BlockRegistry.AQUA_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.INDIGO, BlockRegistry.INDIGO_STAINED_GLASS);
        STAINED_GLASS.put(AllDyes.MAROON, BlockRegistry.MAROON_STAINED_GLASS);

        STAINED_GLASS_PANE.put(AllDyes.WHITE, Blocks.WHITE_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.ORANGE, Blocks.ORANGE_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.MAGENTA, Blocks.MAGENTA_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.YELLOW, Blocks.YELLOW_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.LIME, Blocks.LIME_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.PINK, Blocks.PINK_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.GRAY, Blocks.GRAY_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.CYAN, Blocks.CYAN_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.PURPLE, Blocks.PURPLE_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.BLUE, Blocks.BLUE_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.BROWN, Blocks.BROWN_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.GREEN, Blocks.GREEN_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.RED, Blocks.RED_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.BLACK, Blocks.BLACK_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.AMBER, BlockRegistry.AMBER_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.AQUA, BlockRegistry.AQUA_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.INDIGO, BlockRegistry.INDIGO_STAINED_GLASS_PANE);
        STAINED_GLASS_PANE.put(AllDyes.MAROON, BlockRegistry.MAROON_STAINED_GLASS_PANE);

        FROGLIGHT.put(AllDyes.WHITE, BlockRegistry.CLEAR_FROGLIGHT);
        FROGLIGHT.put(AllDyes.ORANGE, BlockRegistry.MANDARIN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.MAGENTA, BlockRegistry.THULIAN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIGHT_BLUE, BlockRegistry.CERULEAN_FROGLIGHT);
        FROGLIGHT.put(AllDyes.YELLOW, BlockRegistry.LEMON_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIME, BlockRegistry.KIWI_FROGLIGHT);
        FROGLIGHT.put(AllDyes.PINK, BlockRegistry.SAKURA_FROGLIGHT);
        FROGLIGHT.put(AllDyes.GRAY, BlockRegistry.CASCADING_FROGLIGHT);
        FROGLIGHT.put(AllDyes.LIGHT_GRAY, BlockRegistry.CLOUDY_FROGLIGHT);
        FROGLIGHT.put(AllDyes.CYAN, BlockRegistry.TEAL_FROGLIGHT);
        FROGLIGHT.put(AllDyes.PURPLE, Blocks.PEARLESCENT_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BLUE, BlockRegistry.NAVY_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BROWN, BlockRegistry.CHAMOISEE_FROGLIGHT);
        FROGLIGHT.put(AllDyes.GREEN, Blocks.VERDANT_FROGLIGHT);
        FROGLIGHT.put(AllDyes.RED, BlockRegistry.VERMILION_FROGLIGHT);
        FROGLIGHT.put(AllDyes.BLACK, BlockRegistry.CLOUDBURST_FROGLIGHT);
        FROGLIGHT.put(AllDyes.AMBER, Blocks.OCHRE_FROGLIGHT);
        FROGLIGHT.put(AllDyes.AQUA, BlockRegistry.SEAFOAM_FROGLIGHT);
        FROGLIGHT.put(AllDyes.INDIGO, BlockRegistry.LAVENDER_FROGLIGHT);
        FROGLIGHT.put(AllDyes.MAROON, BlockRegistry.SANGUINE_FROGLIGHT);

        SHULKER_BOX.put(AllDyes.WHITE, Blocks.WHITE_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.ORANGE, Blocks.ORANGE_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.MAGENTA, Blocks.MAGENTA_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.YELLOW, Blocks.YELLOW_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIME, Blocks.LIME_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.PINK, Blocks.PINK_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.GRAY, Blocks.GRAY_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.CYAN, Blocks.CYAN_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.PURPLE, Blocks.PURPLE_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BLUE, Blocks.BLUE_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BROWN, Blocks.BROWN_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.GREEN, Blocks.GREEN_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.RED, Blocks.RED_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.BLACK, Blocks.BLACK_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.AMBER, BlockRegistry.AMBER_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.AQUA, BlockRegistry.AQUA_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.INDIGO, BlockRegistry.INDIGO_SHULKER_BOX);
        SHULKER_BOX.put(AllDyes.MAROON, BlockRegistry.MAROON_SHULKER_BOX);

        BED.put(AllDyes.WHITE, Blocks.WHITE_BED);
        BED.put(AllDyes.ORANGE, Blocks.ORANGE_BED);
        BED.put(AllDyes.MAGENTA, Blocks.MAGENTA_BED);
        BED.put(AllDyes.LIGHT_BLUE, Blocks.LIGHT_BLUE_BED);
        BED.put(AllDyes.YELLOW, Blocks.YELLOW_BED);
        BED.put(AllDyes.LIME, Blocks.LIME_BED);
        BED.put(AllDyes.PINK, Blocks.PINK_BED);
        BED.put(AllDyes.GRAY, Blocks.GRAY_BED);
        BED.put(AllDyes.LIGHT_GRAY, Blocks.LIGHT_GRAY_BED);
        BED.put(AllDyes.CYAN, Blocks.CYAN_BED);
        BED.put(AllDyes.PURPLE, Blocks.PURPLE_BED);
        BED.put(AllDyes.BLUE, Blocks.BLUE_BED);
        BED.put(AllDyes.BROWN, Blocks.BROWN_BED);
        BED.put(AllDyes.GREEN, Blocks.GREEN_BED);
        BED.put(AllDyes.RED, Blocks.RED_BED);
        BED.put(AllDyes.BLACK, Blocks.BLACK_BED);
        BED.put(AllDyes.AMBER, BlockRegistry.AMBER_BED);
        BED.put(AllDyes.AQUA, BlockRegistry.AQUA_BED);
        BED.put(AllDyes.INDIGO, BlockRegistry.INDIGO_BED);
        BED.put(AllDyes.MAROON, BlockRegistry.MAROON_BED);
    }
}
